apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fingerscore.fullname" . }}-config
  labels:
    {{- include "fingerscore.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
